import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrument = Instrument_Sans({
  weights: [400, 600, 700],
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={instrument.className}>{children}</body>
    </html>
  );
}
