import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrument = Instrument_Sans({
  weights: [400, 600, 700],
  subsets: ["latin"],
})


export const metadata = {
  title: "Links Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${instrument.className} bg-light`}
    >
      <body className="w-screen min-w-93.75 min-h-dvh  grid place-content-center">{children}</body>
    </html>
  );
}
